name: 'EnvSync'
description: 'A tool to securely sync and load all environment variables and secrets into GitHub Actions, ensuring they are available during runtime.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dynamically load environment variables
      run: |
        echo "Loading all environment variables..."

        # List of known secrets
        declare -a secrets=("TEST_SECRET" "TEST_USERNAME" "MY_ENV")

        # Loop through the known secrets and load them into GitHub Actions environment
        for secret in "${secrets[@]}"; do
          if [[ -n "${{ secrets[$secret] }}" ]]; then
            echo "$secret=${{ secrets[$secret] }}" >> $GITHUB_ENV
          else
            echo "$secret=Variable not found" >> $GITHUB_ENV
          fi
        done

      shell: bash

    - name: Verify Loaded Variables
      run: |
        echo "The environment variables are:"
        printenv  # Print all environment variables to verify they were set
      shell: bash
