name: 'EnvSync'
description: 'A tool to securely sync and load all environment variables and secrets into GitHub Actions, ensuring they are available during runtime.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Load Environment Variables and Secrets
      run: |
        echo "Loading environment variables..."

        # Define an array of secrets manually (replace with actual secrets you want to load)
        declare -a secrets=("TEST_SECRET" "TEST_USERNAME")

        # Iterate over the list of secrets and load them into $GITHUB_ENV
        for secret in "${secrets[@]}"; do
          echo "$secret=${{ secrets[${secret}] }}" >> $GITHUB_ENV
        done

        echo "All secrets have been loaded into environment variables."

      shell: bash

    - name: Verify Loaded Variables
      run: |
        echo "The loaded environment variables are:"
        printenv  # This will display all environment variables to verify they were set

      shell: bash
