name: 'EnvSync'
description: 'A tool to securely sync and load all environment variables and secrets into GitHub Actions, ensuring they are available during runtime.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

name: Load All Environment Variables

on:
  push:
    branches:
      - main

jobs:
  load-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dynamically load all environment variables into GitHub Actions
        run: |
          echo "Loading all environment variables..."

          # Loop through all environment variables and load them dynamically into GitHub Actions environment
          for var in $(printenv | cut -d= -f1); do
            echo "$var=${{ env.${var} }}" >> $GITHUB_ENV
          done

    - name: Check loaded environment variables
      run: |
        echo "Checking environment variables..."
        printenv
      shell: bash  # Use bash as the shell for running the script
