name: "EnvSync"
description: "A tool to securely sync and load all environment variables and secrets into GitHub Actions, ensuring they are available during runtime."

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

      - name: Export GitHub Secrets and Variables
        run: |
          echo "TEST_SECRET=${{ secrets.TEST_SECRET }}" >> $GITHUB_ENV
          echo "TEST_USERNAME=${{ secrets.TEST_USERNAME }}" >> $GITHUB_ENV
          echo "MY_ENV=${{ vars.MY_ENV }}" >> $GITHUB_ENV

      - name: Verify Loaded Variables
        run: |
          echo "The loaded environment variables are"
          printenv  # This will display all environment variables to verify they were set

    - name: Verify Loaded Variables
      run: |
        echo "The loaded environment variables are:"
        printenv  # This will display all environment variables to verify they were set

      shell: bash
