name: 'EnvSync'
description: 'A tool to securely sync and load all environment variables and secrets into GitHub Actions, ensuring they are available during runtime.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Load Environment Variables and Secrets
      run: |
        echo "Loading environment variables..."

        # Manually list secrets (replace with actual secret names)
        echo "TEST_SECRET=${{ secrets.DEV_HOST_USERNAME }}" >> $GITHUB_ENV
        echo "TEST_USERNAME=${{ secrets.TEST_USERNAME }}" >> $GITHUB_ENV
        echo "MY_ENV=${{ vars.MY_ENV }}" >> $GITHUB_ENV

        # Optionally load other environment variables here if needed
        echo "MY_ENV_VAR=${{ vars.MY_ENV_VAR }}" >> $GITHUB_ENV

        echo "All secrets and environment variables have been loaded into GitHub Actions."

      shell: bash

    - name: Verify Loaded Variables
      run: |
        echo "The loaded environment variables are:"
        printenv  # This will display all environment variables to verify they were set

      shell: bash
